-- This script modifies Virtuoso to support r&wbase. 
-- WARNING: running this script deletes all triples

-- 1. Change table: CREATE EXTRA INTEGER COLUMN
DROP TABLE DB.DBA.RDF_QUAD;

CREATE TABLE DB.DBA.RDF_QUAD (
  G IRI_ID_8,
  S IRI_ID_8,
  P IRI_ID_8,
  O ANY,
  DA INTEGER DEFAULT -1,
  PRIMARY KEY (P, S, O, G, DA)
  )
ALTER INDEX RDF_QUAD ON DB.DBA.RDF_QUAD 
  PARTITION (S INT (0hexffff00));

CREATE DISTINCT NO PRIMARY KEY REF BITMAP INDEX RDF_QUAD_SP 
  ON RDF_QUAD (S, P) 
  PARTITION (S INT (0hexffff00));

CREATE BITMAP INDEX RDF_QUAD_POGS 
  ON RDF_QUAD (P, O, G, S) 
  PARTITION (O VARCHAR (-1, 0hexffff));

CREATE DISTINCT NO PRIMARY KEY REF BITMAP INDEX RDF_QUAD_GS 
  ON RDF_QUAD (G, S) 
  PARTITION (S INT (0hexffff00));

CREATE DISTINCT NO PRIMARY KEY REF INDEX RDF_QUAD_OP 
  ON RDF_QUAD (O, P) 
  PARTITION (O VARCHAR (-1, 0hexffff));

RDF_GLOBAL_RESET();

-- Extra optional indexes

-- CREATE BITMAP INDEX RDF_QUAD_OPGSDA
--  ON DB.DBA.RDF_QUAD (O, P, G, S, DA) 
--  PARTITION (O VARCHAR (-1, 0hexffff));

-- CREATE BITMAP INDEX RDF_QUAD_SPOGDA 
--  ON RDF_QUAD (S, P, O, G, DA) 
--  PARTITION (P VARCHAR (-1, 0hexffff));
